### PR TITLE
fix: remove unnecessary magic checks

### LINKED ISSUE #19: sasquatch can't handle version 2 with non-standard (sqlz) magic
The attached sample ([09bc2ac3b35d7475f6d2e2283c73ea275a9d6876.zip](https://github.com/onekey-sec/sasquatch/files/12289492/09bc2ac3b35d7475f6d2e2283c73ea275a9d6876.zip)) comes from a [TrendNet firmware](https://www.trendnet.com/langge/support/support-detail.asp?prod=195_TEW-657BRM).

When trying to extract it with sasquatch, we get the following output:

```
sasquatch -be /tmp/sample.sqlz
Non-standard SquashFS Magic: 'sqlz'
Reading a different endian SQUASHFS filesystem on /tmp/sample.sqlz
FATAL ERROR: Can't find a valid SQUASHFS superblock on /tmp/sample.sqlz
```

The old sasquatch version running on squashfs-tools 4.3 can extract the sample. We need to investigate which patch made it stop working and find a fix. Probably similar to https://github.com/onekey-sec/sasquatch/pull/18

Reported by @m-1-k-3

### PR DESCRIPTION
**Pull request by jstucke**
Remove unnecessary magic checks so that squashfs variants of v2 and v4 with non-standard magic (e.g. sqlz or shsq) may be unpacked.

Should fix #19 

needed for https://github.com/onekey-sec/unblob/pull/1352 and apparently also https://github.com/onekey-sec/unblob/pull/639

### CODE REVIEW

File: squashfs-tools/unsquash-2.c [hunk 1]
```diff
@@ -590,8 +590,7 @@ int read_super_2(squashfs_operations **s_ops, void *s)
 {
 	 squashfs_super_block_3 *sBlk_3 = s;
 
-	if(sBlk_3->s_magic != SQUASHFS_MAGIC || sBlk_3->s_major != 2 ||
```
Comment (martonilles) [inline squashfs-tools/unsquash-2.c:593]: I would rather extend the list of known magics instead of dropping the check altogether.

Comment (jstucke) [reply squashfs-tools/unsquash-2.c:593]: Are you sure that is the best approach? Then you have to keep a list of known formats and change the code each time a new one pops up

The current state:
- there is a global magic check but it only checks for the standard magic (in BE and LE) and logs a warning if it does not match
- the magic checks that I patched out are in the methods that read in the v2/v4 header (again only check for the standard magic)
- there is no analogous check in the method that reads in the v3 header (that's why it works with other magic values in unblob in v3)
- there are plenty of sanity checks for things like the block size. 

IMHO this should be either part of the global check or removed altogether, but they way it is now does not make a lot of sense. Another option might be a new CLI parameter to either ignore the magic value or expect a different one.

Comment (martonilles) [reply squashfs-tools/unsquash-2.c:593]: Good argument, considering the goal of sasquatch is to unpack "any" squashfs format, dropping this would be OK, worth case that the extraction would fail at a later point. As pointed out non-standard magic is already logged in https://github.com/onekey-sec/sasquatch/blob/main/squashfs-tools/unsquashfs.c#L2290

**Review by martonilles — APPROVED** [review]

**Review by qkaiser — APPROVED** [review]
